### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by fshenton** [fshenton/vikings#23]
- [x] Add time estimates

- [x] Draw up wireframes of page (5m / 5m)
    - [x] Mobile portrait
    - ~same on all others

- [x] Grab spacing and sizing from Flo's designs (30m / 1hr) 
    - [x] Remove guides, add own
    - [x] Fonts
    - [x] Element positioning/spacing
    - [x] Find relationships between sizes and spacing

- [x] Issues for the devices

- [x] Branch (BEM)

- [x] Implement Layouts
    - [x] Mobile
    - [x] Desktop
    - [x] Tablet

- [x] Make PR 

- [x] PR Feedback (1hr / 1h22) 

- [x] PR Feedback
    - [x] Reducer refactor (40m / 1h20)
    - [x] Socials styling (1h /1h)

- [x] Merge back to layout

**Comment by pookage** [comment]
Heads up! "gutters / rows / columns" implies a css grid - best to stay agnostic with 'spacing' instead of hemming yourself in with an implementation this early
